image: $CONTAINER_TEST_IMAGE

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME

stages:
  - build_docker
  - testing

build_docker_from_scratch:
  only:
    - schedules
  image: docker
  stage: build_docker
  before_script:
    - ls
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE --no-cache .
    - docker push $CONTAINER_TEST_IMAGE

build_docker_from_cache:
  except:
    - schedules
  image: docker
  stage: build_docker
  before_script:
    - ls
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

mytest:
  stage: testing
  script:
    - pip3 install resolve
    - pytest-3 -q --cov=resolve test
  coverage: '/^TOTAL.+?(\d+\%)$/'

test_mpi:
  stage: testing
  variables:
    OMPI_MCA_btl_vader_single_copy_mechanism: none
  script:
    - pip3 install resolve
    - mpiexec -n 2 --bind-to none pytest-3 -q test/test_mpi

# staticchecks:
#   stage: testing
#   script:
#     - flake8 .
