image: $CONTAINER_TEST_IMAGE

variables:
  CONTAINER_TEST_IMAGE: gitlab-registry.mpcdf.mpg.de/$CI_PROJECT_PATH:$CI_BUILD_REF_NAME
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build_docker
  - testing
  - release

build_docker_from_scratch:
  only:
    - schedules
  image: docker
  stage: build_docker
  before_script:
    - ls
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE --no-cache .
    - docker push $CONTAINER_TEST_IMAGE

build_docker_from_cache:
  except:
    - schedules
  image: docker
  stage: build_docker
  before_script:
    - ls
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN gitlab-registry.mpcdf.mpg.de
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

before_script:
  - pip3 install --user .
  - cd resolvelib && pip3 install --user . && cd ..

test_resolve:
  stage: testing
  script:
    - pytest-3 -q --cov=resolve test
  coverage: '/^TOTAL.+?(\d+\%)$/'

test_resolvelib:
  stage: testing
  script:
    - cd resolvelib && pytest-3 -q test
    - python3 demos/bench.py quick

test_resolve_mpi:
  stage: testing
  variables:
    OMPI_MCA_btl_vader_single_copy_mechanism: none
  script:
    - mpiexec -n 2 --bind-to none pytest-3 -q test/test_mpi

pages:
  stage: release
  script:
    - rm -rf docs/build docs/source/mod
    - sh docs/generate.sh
    - mv docs/build public
  artifacts:
    paths:
      - public
  only:
    - master

