name: resolve-tests
on: [push]
jobs:
  test-standard:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, windows-2022]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: sudo apt update && sudo apt install -y python3-mpi4py
      - run: python -m pip install --user --upgrade setuptools pybind11 pytest
      - run: python -m pip install --user .
      - run: python -m pytest python/test -x
