name: resolve-tests
on: [push]
jobs:
  test-standard:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-11.0, windows-2022]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --user --upgrade setuptools pybind11 pytest numpy scipy
      - run: python -m pip install --user .
      - run: python -m pytest python/test -x
  test-intel:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install --user --upgrade setuptools pybind11 pytest scipy
      - run: sudo apt update
      # fix this version for now, because the current one has trouble installing
      - run: |
          CC=icx CXX=icpx python3 -m pip install --user .
          python -m pytest python/test -x
